library(shinycssloaders)
library(Seurat)


stages <- c("<select>", list.files("data"))
clusters <- c("<select>")
genes <- c("<select>")

object <- NULL

clustering <- NULL

clustering <- c(
	"res.4.5",
	"res.4",
	"res.5",
	"res.5",
	"res.4.5",
	"res.5",
	"res.6",
	"res.6",
	"res.5",
	"res.5.5",
	"res.6",
	"res.5"
)

files <- c(
	"zf6s_cc_filt.cluster.rds",
	"zf10s_cc_filt.cluster.rds",
	"zf14s_cc_filt.cluster.rds",
	"zf18s_cc_filt.cluster.rds",
	"zf20hpf_cc_filt.cluster.rds",
	"zf24hpf_cc_filt.cluster.rds",
	"zf36hpf_cc_filt.cluster.rds",
	"zf2dpf_cc_filt.cluster.rds",
	"zf3dpf_cc_filt.cluster.rds",
	"zf5dpf_cc_filt.cluster.rds",
	"zf8dpf_cc_filt.cluster4.rds",
	"zf15dpf_PCAALL"
)

colors.to.use <- c(
	"pink1",
	"gold",
	"cyan3",
	"wheat3",
	"palegreen3",
	"skyblue1",
	"goldenrod",
	"sandybrown",
	"lightseagreen",
	"khaki3",
	"green3",
	"aquamarine3",
	"plum",
	"yellowgreen",
	"darkorange",
	"cornsilk3",
	"turquoise2",
	"orchid",
	"mediumpurple2",
	"chartreuse3",
	"seagreen3",
	"pink4",
	"slateblue1",
	"lemonchiffon2",
	"darkslategray3",
	"darkolivegreen3",
	"coral",
	"palevioletred",
	"darkgoldenrod2",
	"darksalmon",
	"sienna1",
	"steelblue1",
	"slategray2",
	"chocolate1",
	"lightgreen",
	"cadetblue3",
	"salmon",
	"yellow3",
	"thistle",
	"burlywood",
	"khaki",
	"mistyrose2",
	"azure3",
	"tomato",
	"darkseagreen3",
	"pink2",
	"lightgoldenrod",
	"peachpuff2",
	"grey70",
	"rosybrown3",
	"deepskyblue",
	"lavenderblush3",
	"lemonchiffon",
	"powderblue",
	"springgreen3",
	"bisque3",
	"lightcyan3",
	"gold3",
	"lightsalmon",
	"darkkhaki",
	"darkorchid2",
	"gray40",
	"hotpink",
	"lightgrey",
	"cyan2",
	"slategray3",
	"azure2",
	"wheat2",
	"mediumpurple",
	"darkgoldenrod3",
	"grey80",
	"mistyrose",
	"lavenderblush2",
	"seagreen2",
	"khaki2",
	"yellow2",
	"peachpuff",
	"rosybrown4",
	"springgreen2",
	"bisque2",
	"cornsilk2",
	"steelblue2",
	"sienna2",
	"aquamarine2",
	"palegreen2",
	"pink3",
	"darkolivegreen2",
	"steelblue3",
	"goldenrod3",
	"darkorchid",
	"brown",
	"indianred",
	"lemonchiffon4",
	"moccasin",
	"grey",
	"honeydew2",
	"coral2",
	"chocolate4",
	"darkturquoise",
	"firebrick2",
	"blueviolet"
)

clustering.data <- data.frame(files, clustering)
